import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Header, LoadingOverlay } from "@/components/common";
import dotenv from "dotenv";
import React from "react";
import { LanguageProvider } from "@/contexts/language.context";

dotenv.config({ path: ".env" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MovieStream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`hide-scrollbar ${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased flex flex-col">
        <LanguageProvider>
          <LoadingOverlay />
          <Header />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
